# Generated by Django 6.1 on 2026-09-03 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isbn13",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="ISBN13은 ASCII 숫자 13자리여야 합니다.",
                                regex="\\A[0-9]{13}\\Z",
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("authors", models.CharField(blank=True, max_length=500)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("cover_url", models.URLField(blank=True, max_length=1000)),
                ("description", models.TextField(blank=True)),
                ("table_of_contents", models.TextField(blank=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("isbn13__regex", "^[0-9]{13}$")),
                        name="books_book_isbn13_ascii_digits",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("title__gt", "")),
                        name="books_book_title_not_empty",
                    ),
                ],
            },
        ),
    ]
