# Generated by Django 6.1 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("theme", "Theme"),
                            ("argument", "Argument"),
                            ("concept", "Concept"),
                            ("character", "Character"),
                            ("event", "Event"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_claims",
                        to="books.book",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "kind__in",
                                ("theme", "argument", "concept", "character", "event"),
                            )
                        ),
                        name="knowledge_bookknowledge_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("content__regex", "\\S")),
                        name="knowledge_bookknowledge_content_not_blank",
                    ),
                    models.UniqueConstraint(
                        fields=("book", "kind", "content"),
                        name="knowledge_bookknowledge_book_kind_content_uniq",
                    ),
                ],
            },
        ),
    ]
