# Generated by Django 6.1 on 2026-09-08 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("readings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "knowledge_readiness",
                    models.CharField(
                        choices=[("READY", "준비됨"), ("READY_LIMITED", "제한됨")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "진행 중"),
                            ("REFLECTION_READY", "Reflection 준비 완료"),
                            ("COMPLETED", "완료"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="books.book"
                    ),
                ),
                (
                    "reading",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="readings.reading",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewTurn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("question", models.CharField(max_length=2000)),
                ("answer", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turns",
                        to="reflections.interview",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence", "id"),
            },
        ),
        migrations.AddConstraint(
            model_name="interview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("knowledge_readiness__in", ("READY", "READY_LIMITED"))
                ),
                name="reflections_interview_readiness_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="interview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("IN_PROGRESS", "REFLECTION_READY", "COMPLETED"))
                ),
                name="reflections_interview_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)),
                name="reflections_turn_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewturn",
            constraint=models.CheckConstraint(
                condition=models.Q(("question__regex", "\\S")),
                name="reflections_turn_question_not_blank",
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewturn",
            constraint=models.UniqueConstraint(
                fields=("interview", "sequence"),
                name="reflections_turn_interview_sequence_uniq",
            ),
        ),
    ]
