# Generated by Django 6.1 on 2026-09-10

from django.db import migrations, models

from reflections.models import default_coverage

DEFAULT_COVERAGE = {
    "MEMORY": "UNCOVERED",
    "REACTION": "UNCOVERED",
    "CONNECTION": "UNCOVERED",
    "AFTERTHOUGHT": "UNCOVERED",
}


class Migration(migrations.Migration):
    dependencies = [("reflections", "0001_initial")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "SET LOCAL lock_timeout = '2s'; "
                        "ALTER TABLE reflections_interview ADD COLUMN coverage jsonb "
                        "NOT NULL DEFAULT "
                        '\'{"MEMORY": "UNCOVERED", "REACTION": "UNCOVERED", '
                        '"CONNECTION": "UNCOVERED", '
                        '"AFTERTHOUGHT": "UNCOVERED"}\'::jsonb;'
                    ),
                    reverse_sql=(
                        "SET LOCAL lock_timeout = '2s'; "
                        "ALTER TABLE reflections_interview DROP COLUMN coverage;"
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="interview",
                    name="coverage",
                    field=models.JSONField(
                        db_default=models.Value(
                            DEFAULT_COVERAGE, output_field=models.JSONField()
                        ),
                        default=default_coverage,
                    ),
                )
            ],
        )
    ]
