# Generated by Django 6.1 on 2026-09-10

from django.db import migrations, models
from django.db.models.expressions import RawSQL

CONSTRAINT_NAME = "reflections_interview_coverage_canonical"
COVERAGE_AXES_SQL = "ARRAY['MEMORY', 'REACTION', 'CONNECTION', 'AFTERTHOUGHT']"
CONSTRAINT_SQL = f"""
jsonb_typeof(coverage) = 'object'
AND (coverage - {COVERAGE_AXES_SQL}::text[]) = '{{}}'::jsonb
AND coverage ?& {COVERAGE_AXES_SQL}
AND (coverage->>'MEMORY') IN ('UNCOVERED', 'PARTIAL', 'COVERED')
AND (coverage->>'REACTION') IN ('UNCOVERED', 'PARTIAL', 'COVERED')
AND (coverage->>'CONNECTION') IN ('UNCOVERED', 'PARTIAL', 'COVERED')
AND (coverage->>'AFTERTHOUGHT') IN ('UNCOVERED', 'PARTIAL', 'COVERED')
""".strip()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [("reflections", "0002_interview_coverage")]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "BEGIN; SET LOCAL lock_timeout = '2s'; "
                        "ALTER TABLE reflections_interview ADD CONSTRAINT "
                        f"{CONSTRAINT_NAME} "
                        f"CHECK ({CONSTRAINT_SQL}) NOT VALID; COMMIT;"
                    ),
                    reverse_sql=(
                        "BEGIN; SET LOCAL lock_timeout = '2s'; "
                        "ALTER TABLE reflections_interview DROP CONSTRAINT "
                        f"{CONSTRAINT_NAME}; "
                        "COMMIT;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        "ALTER TABLE reflections_interview VALIDATE CONSTRAINT "
                        f"{CONSTRAINT_NAME};"
                    ),
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name="interview",
                    constraint=models.CheckConstraint(
                        condition=RawSQL(
                            CONSTRAINT_SQL,
                            params=(),
                            output_field=models.BooleanField(),
                        ),
                        name=CONSTRAINT_NAME,
                    ),
                )
            ],
        )
    ]
