# Generated by Django 6.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reflections", "0003_interview_coverage_constraint")]

    operations = [
        migrations.RunSQL(
            "SET LOCAL lock_timeout = '2s';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="interviewturn",
            name="next_question_skipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
