# Generated by Django 6.1 on 2026-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reflections", "0005_interview_progress_decision"),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL lock_timeout = '2s';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="interviewprogressdecision",
            name="candidate_focus_axis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MEMORY", "MEMORY"),
                    ("REACTION", "REACTION"),
                    ("CONNECTION", "CONNECTION"),
                    ("AFTERTHOUGHT", "AFTERTHOUGHT"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
