# Generated by Django 6.1 on 2026-09-15 14:06

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reflections", "0006_interviewprogressdecision_candidate_focus_axis"),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL lock_timeout = '2s';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="Reflection",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("draft_markdown", models.TextField()),
                ("draft_sections", models.JSONField()),
                ("revised_markdown", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "초안")], default="DRAFT", max_length=20
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection",
                        to="reflections.interview",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status", "DRAFT")),
                        name="reflections_reflection_status_draft",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("completed_at__isnull", True)),
                        name="reflections_reflection_completed_at_null",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.expressions.RawSQL(
                            "char_length(draft_markdown) >= 1 "
                            "AND char_length(draft_markdown) <= 22000 "
                            "AND length(trim(draft_markdown)) > 0",
                            output_field=models.BooleanField(),
                            params=(),
                        ),
                        name="reflections_reflection_draft_markdown_valid",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.expressions.RawSQL(
                            "revised_markdown IS NULL OR ("
                            "char_length(revised_markdown) >= 1 "
                            "AND char_length(revised_markdown) <= 20000 "
                            "AND length(trim(revised_markdown)) > 0)",
                            output_field=models.BooleanField(),
                            params=(),
                        ),
                        name="reflections_reflection_revised_markdown_valid",
                    ),
                    models.CheckConstraint(
                        condition=django.db.models.expressions.RawSQL(
                            "jsonb_typeof(draft_sections) = 'array'",
                            output_field=models.BooleanField(),
                            params=(),
                        ),
                        name="reflections_reflection_draft_sections_array",
                    ),
                ],
            },
        ),
    ]
