# Generated by Django 6.1 on 2026-09-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reflections", "0007_reflection"),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL lock_timeout = '2s';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name="interviewturn",
            name="user_skipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="interview",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_PROGRESS", "진행 중"),
                    ("REFLECTION_READY", "Reflection 준비 완료"),
                    ("COMPLETED", "완료"),
                    ("ENDED_NO_REFLECTION", "답변 부족 종결"),
                ],
                default="IN_PROGRESS",
                max_length=20,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "reflections_interview" '
                        "DROP CONSTRAINT IF EXISTS "
                        '"reflections_interview_status_valid"; '
                        'ALTER TABLE "reflections_interview" '
                        'ADD CONSTRAINT "reflections_interview_status_valid" '
                        "CHECK (status IN ('IN_PROGRESS', 'REFLECTION_READY', "
                        "'COMPLETED', 'ENDED_NO_REFLECTION')) NOT VALID;"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "reflections_interview" '
                        "DROP CONSTRAINT IF EXISTS "
                        '"reflections_interview_status_valid"; '
                        'ALTER TABLE "reflections_interview" '
                        'ADD CONSTRAINT "reflections_interview_status_valid" '
                        "CHECK (status IN ('IN_PROGRESS', 'REFLECTION_READY', "
                        "'COMPLETED')) NOT VALID;"
                    ),
                ),
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE "reflections_interviewturn" '
                        'ADD CONSTRAINT "reflections_turn_result_mutually_exclusive" '
                        "CHECK (answer IS NULL OR user_skipped_at IS NULL) NOT VALID;"
                    ),
                    reverse_sql=(
                        'ALTER TABLE "reflections_interviewturn" '
                        "DROP CONSTRAINT IF EXISTS "
                        '"reflections_turn_result_mutually_exclusive";'
                    ),
                ),
            ],
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="interview",
                    name="reflections_interview_status_valid",
                ),
                migrations.AddConstraint(
                    model_name="interview",
                    constraint=models.CheckConstraint(
                        condition=models.Q(
                            status__in=(
                                "IN_PROGRESS",
                                "REFLECTION_READY",
                                "COMPLETED",
                                "ENDED_NO_REFLECTION",
                            )
                        ),
                        name="reflections_interview_status_valid",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="interviewturn",
                    constraint=models.CheckConstraint(
                        condition=models.Q(answer__isnull=True)
                        | models.Q(user_skipped_at__isnull=True),
                        name="reflections_turn_result_mutually_exclusive",
                    ),
                ),
            ],
        ),
    ]
