# Generated by Django 6.1 on 2026-09-16

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("reflections", "0008_interview_turn_user_skip"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "reflections_interview" '
                'VALIDATE CONSTRAINT "reflections_interview_status_valid";'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql=(
                'ALTER TABLE "reflections_interviewturn" '
                'VALIDATE CONSTRAINT "reflections_turn_result_mutually_exclusive";'
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
