# Generated by Django 6.1 on 2026-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reflections", "0009_validate_interview_turn_user_skip"),
    ]

    operations = [
        migrations.RunSQL(
            "SET LOCAL lock_timeout = '2s';",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveConstraint(
            model_name="reflection",
            name="reflections_reflection_status_draft",
        ),
        migrations.RemoveConstraint(
            model_name="reflection",
            name="reflections_reflection_completed_at_null",
        ),
        migrations.AlterField(
            model_name="reflection",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "초안"), ("COMPLETED", "완료")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="reflection",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("DRAFT", "COMPLETED"))),
                name="reflections_reflection_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reflection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "DRAFT"), ("completed_at__isnull", True)),
                    models.Q(("status", "COMPLETED"), ("completed_at__isnull", False)),
                    _connector="OR",
                ),
                name="reflections_reflection_status_completed_at_consistent",
            ),
        ),
    ]
