# Generated by Django 6.1 on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("want_to_read", "읽고 싶음"),
                            ("reading", "읽는 중"),
                            ("completed", "완독"),
                        ],
                        max_length=20,
                    ),
                ),
                ("completed_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("completed_on__isnull", False), ("status", "completed")
                            )
                            | (
                                ~models.Q(("status", "completed"))
                                & models.Q(("completed_on__isnull", True))
                            )
                        ),
                        name="readings_completion_date_state",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("want_to_read", "reading"))),
                        fields=("user", "book"),
                        name="readings_active_user_book_uniq",
                    ),
                ],
            },
        ),
    ]
